### ISSUE TITLE
[Small Typo] Template not found

### ISSUE THREAD

**Issue by drblaui** [LiveReader/graphly-d3#112]
The "found" in the following error messages has two n's. Nothing major, but still worth reporting :)

https://github.com/LiveReader/graphly-d3/blob/b757d5e09ae1fe100d408f61085df2fd9d2608ff/lib/simulation/templateStore.ts#L42

**Comment by jason-rietzke** [comment]
Oh yeah, that's a good hint, we'll fix that in the next release cycle
